-- Script para recrear la tabla con latitud y longitud
DROP TABLE IF EXISTS public.charging_points;

CREATE TABLE public.charging_points (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    region TEXT,
    province TEXT,
    city_or_canton TEXT NOT NULL,
    name TEXT NOT NULL,
    speed TEXT,
    charger_type TEXT,
    power TEXT,
    schedule TEXT,
    cost_type TEXT,
    gps_link TEXT,
    lat NUMERIC,
    lng NUMERIC,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
ALTER TABLE public.charging_points ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir lectura pública de puntos de carga" ON public.charging_points FOR SELECT USING (true);
  
BEGIN;
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Esmeraldas', 'La Unión', 'Lubricentro Brito', '🟡 NORMAL', '220V 32A Pata Gallina', '7kW', '24/7', 'Gratuito*', 'https://maps.app.goo.gl/F2TgyEFGJw1hRH716', -0.3014656, -78.4662528);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Esmeraldas', 'La Concordia', 'Ultra NRG Gasolinera Multiservicios', '🟡 NORMAL', 'Tipo 2 Pared', '7kW', '24/7', 'Consultar', 'https://maps.app.goo.gl/utE8PqRRsRtekjDk8', -0.0148146, -79.3780399);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Esmeraldas', 'San Mateo', 'Gasolinera P&S San Mateo', '🟡 NORMAL', '220V 32A Pata Gallina', '7kW', '24/7', 'Gratuito*', 'https://maps.app.goo.gl/kcio9fEoDLdSW3Xh8', 0.8769098, -79.6376649);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Esmeraldas', 'Tonsupa', 'Castelnuovo', '🟡 NORMAL', '220V 32A Pata Gallina', '7kW', 'Tarde', 'Gratuito*', 'https://maps.app.goo.gl/qAU3nMLdvvS6VLX48', 0.8818976, -79.8326762);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Esmeraldas', 'Salima', 'Gasolinera PetroRíos San Luis', '🟡 NORMAL', '220V 32A Pata Gallina', '7kW', '24/7', 'Gratuito*', 'https://maps.app.goo.gl/cfFQ58fbrtWs4LgT7', -0.3014656, -78.4662528);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Esmeraldas', 'Atacames', 'Taller Don Milton', '🟡 NORMAL', '220V 32A Pata Gallina', '7kW', 'Tarde', 'Gratuito*', 'https://maps.app.goo.gl/ANeMBL7UeQ51kqJv5', 0.8685172, -79.8528036);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Santo Domingo', 'Santo Domingo', 'KFC Santo Domingo — EVINKA CONECT', '🟢 RÁPIDA', 'Tipo 2 + CS2', '7kW / 60kW', '24/7', 'Pago', 'https://maps.app.goo.gl/jRtjsbneP1PCLcXx8', -0.2622591, -79.1149259);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Santo Domingo', 'Santo Domingo', 'BYD Bomboli Shopping — EVINKA CONECT', '🟢 RÁPIDA', 'Tipo 2 + CS2', '7kW / 60kW', 'Lun-Dom 10am-9pm', 'Pago', 'https://maps.app.goo.gl/yDGX4RRYnq42dWWA7', -0.2536416, -79.1927794);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Santo Domingo', 'Santo Domingo', 'BYD Bomboli Shopping — CONDOR CHARGE', '🟢 RÁPIDA', 'Tipo 2 + CS2', '7kW / 60kW', 'Lun-Dom 10am-9pm', 'Pago', 'https://maps.app.goo.gl/yDGX4RRYnq42dWWA7', -0.2536416, -79.1927794);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Santo Domingo', 'Santo Domingo', 'Club del Campo Hotel & Convenciones', '🟡 NORMAL', '220V 32A Pata Gallina', '7kW', 'Tarde', 'Gratuito*', 'https://maps.app.goo.gl/JsukMbBhpZDZutfa6', -0.2339237, -79.1345977);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Santo Domingo', 'Santo Domingo', 'Hostería Los Colorados', '🟡 NORMAL', 'Tipo 2 Pared', '7kW', '24/7', 'Gratuito*', 'https://maps.app.goo.gl/Bui7YmsbNHU37qb58', -0.2729919, -79.0798772);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Santo Domingo', 'Cerca de Aloag', 'Vulcanizadora Recinto La Virgen', '🟡 NORMAL', '220V 32A Pata Gallina', '7kW', '24/7', 'Gratuito*', 'https://maps.app.goo.gl/wWewNPJu1orB7fvV6', -0.4417288, -78.7453146);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Santo Domingo', 'Luz de América', 'Frente al Comercial Ponce', '🟡 NORMAL', '220V 32A Pata Gallina', '7kW', 'Tarde', 'Gratuito*', 'https://maps.app.goo.gl/dToQjP5YywexHsvs7', -0.4035438, -79.2991432);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Los Ríos', 'Patricia Pilar', 'Vulcanizadora', '🟡 NORMAL', '220V 32A Pata Gallina', '7kW', 'Tarde', 'Gratuito*', 'https://goo.gl/maps/NTV8uTJyumMSdgnX8', NULL, NULL);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Los Ríos', 'Babahoyo', 'Punto de Carga Comunidad BYD — Pueblo Nuevo', '🟡 NORMAL', 'Tipo 2 Pared', '7kW', '24/7 — Agendar', 'Solo miembros BYD', 'RESERVADO - SOLO MIEMBROS BYD', NULL, NULL);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Guayas', 'Guayaquil', 'BYD Juan Tanga Marengo', '🟢 RÁPIDA', 'Tipo 2 + CS2', '7kW / 60kW', 'Lun-Vie 9am-6pm / Sáb 10am-2pm', 'Pago', 'https://maps.app.goo.gl/1BDtbuHnVYeURAhW7', -0.3014656, -78.4662528);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Guayas', 'Guayaquil', 'BYD Américas', '🟡 NORMAL', 'Tipo 2 Pared', '7kW', 'Lun-Vie 9am-6pm / Sáb 10am-2pm', 'Pago', 'https://maps.app.goo.gl/h4JYzTDghEkhpUUq6', -2.1429496, -79.8841688);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Guayas', 'Guayaquil', 'Mall del Norte', '🟡 NORMAL', 'Tipo 1 + Tipo 2', '7kW', 'Hasta 9pm', 'Gratuito*', 'https://maps.app.goo.gl/VZKWDhXmuSWNsUKt7', -0.3014656, -78.4662528);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Guayas', 'Guayaquil', 'City Mall', '🟡 NORMAL', 'Tipo 1 Pared', '7kW', 'Hasta 9pm', 'Gratuito*', 'https://maps.app.goo.gl/QLgm9YUowbwG1fpQ7', -0.311296, -78.4760832);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Guayas', 'Guayaquil', 'Parque Samanes — CONDOR CHARGE', '🟢 RÁPIDA', 'CS2 + CHAdeMO + Tipo 2', '40kW / 40kW / 7kW', 'Abierto excepto 6pm-10pm', 'Pago', 'https://maps.app.goo.gl/KCp9jK1nZcG49SGF8', -2.1022715, -79.8895345);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Guayas', 'Guayaquil', 'Megamaxi Ceibos — CONDOR CHARGE', '🟢 RÁPIDA', 'CS2 — PRÓXIMAMENTE', '60kW', '9am-9pm', 'Pago', 'https://maps.app.goo.gl/ezQfESXhXVwWkttk7', -2.1735755, -79.9397505);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Guayas', 'Guayaquil Vía la Costa', 'Primax Puerto Azul', '🟡 NORMAL', 'Tipo 1 Pared', '7kW', '24/7', 'Gratuito*', 'https://maps.app.goo.gl/6rCv1ZnmQ7NwcUmr8', -2.1860446, -79.9728705);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Guayas', 'Guayaquil Vía la Costa', 'Burger King — EVINKA CONECT', '🟡 NORMAL', 'Tipo 2 Pared', '7kW', 'Lun-Dom 10am-1am', 'Pago', 'https://maps.app.goo.gl/iJerLjoe8xr6BrZQ8', -2.183065, -79.981516);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Guayas', 'Durán', 'Punto Carga Comunidad BYD — Panorama', '⚫ PRIVADO', 'Tipo 2 Pared', '7kW', '6am-11pm — Agendar', 'Solo miembros BYD', 'RESERVADO - SOLO MIEMBROS BYD', NULL, NULL);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Guayas', 'Samborondón', 'Punto Carga Comunidad BYD — Ciudad Celeste', '⚫ PRIVADO', 'Tipo 2 Pared', '7kW', '24/7 — Agendar', 'Solo miembros BYD', 'RESERVADO - SOLO MIEMBROS BYD', NULL, NULL);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Guayas', 'Samborondón', 'Plaza Lagos', '🟡 NORMAL', 'Tipo 2 Pared', '7kW', '8am-11pm', 'Gratuito*', 'https://maps.app.goo.gl/ZzqYfXX2Dj2dnfpq8', -2.1258928, -79.8634548);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Guayas', 'Samborondón', 'Village', '🟡 NORMAL', 'Tipo 1 Pared (Adaptador)', '3.5kW', '10am-9pm', 'Gratuito*', 'https://maps.app.goo.gl/YdKxtRXf4Sz7qHzR6', -2.1400272, -79.8644987);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Guayas', 'Samborondón', 'Marbol Plaza', '🟡 NORMAL', 'Tipo 2 Pared', '7kW', '8am-10pm', 'Gratuito*', 'https://maps.app.goo.gl/ZzqYfXX2Dj2dnfpq8', -2.1258928, -79.8634548);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Guayas', 'Samborondón', 'Parque La Paz Aurora', '🟡 NORMAL', 'Tipo 2 Pared', '3.5kW', '24/7', 'Gratuito*', 'https://maps.app.goo.gl/S8JCDE5z7poBjfSe8', -2.0508396, -79.8998371);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Guayas', 'Playas Villamil', 'Punto Carga Comunidad BYD', '⚫ PRIVADO', 'Tipo 2 Pared', '7kW', '24/7 — Agendar', 'Solo miembros BYD', 'RESERVADO - SOLO MIEMBROS BYD', NULL, NULL);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Guayas', 'Playas Villamil', 'La Costa Club de Campo', '🟡 NORMAL', 'Tipo 2 Pared', '7kW', '8am-5pm', 'Gratuito*', 'https://maps.app.goo.gl/WUT2zb4CSkAtiee2A', -2.2648851, -80.1511622);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Guayas', 'Playas Villamil', 'Hotel Presidente Premium', '🟡 NORMAL', '220V Tipo Chino + Pata Gallina', '3.5-7kW', '24/7', 'Gratuito*', 'https://maps.app.goo.gl/pFDGh8JBzmTAe2nn9', -2.6600364, -80.3742229);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Guayas', 'Playas Villamil', 'Hotel Luna Azzul', '🟡 NORMAL', '220V 16A-32A', '3.5-7kW', '24/7', 'Gratuito*', 'https://maps.app.goo.gl/fsoWacmttjkHzHSa8', -2.6417404, -80.3873521);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Chimborazo', 'Bucay', 'Cascada La Poderosa — Vía Chillanes', '🟡 NORMAL', '220V 32A Pata Gallina', '7kW', 'Hasta la tarde', 'Gratuito*', 'https://maps.app.goo.gl/qdR55sDkETPKqKkA9', -2.1310451, -79.1179069);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Guayas', 'Naranjal', 'Punto Carga Comunidad BYD', '⚫ PRIVADO', 'Tipo 2 Pared', '7kW', '24/7 — Agendar', 'Solo miembros BYD', 'RESERVADO - SOLO MIEMBROS BYD', NULL, NULL);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Santa Elena', 'Santa Elena', 'Punto Carga Comunidad BYD', '⚫ PRIVADO', 'Tipo 2 Pared', '7kW', '24/7 — Agendar', 'Solo miembros BYD', 'RESERVADO - SOLO MIEMBROS BYD', NULL, NULL);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Santa Elena', 'Santa Elena', 'Vulcanizadora junto a Mago Fast Food', '🟡 NORMAL', '220V 32A Pata Gallina', '7kW', 'Hasta la tarde', 'Gratuito*', 'https://maps.app.goo.gl/wmncQ8aeED4TGH5bA', -2.2312822, -80.8647349);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Santa Elena', 'Santa Elena', 'Terminal de Santa Elena', '🟡 NORMAL', 'Tipo 2 Pared', '7kW', '24/7', 'Gratuito*', 'https://maps.app.goo.gl/wHREtfHZzsL6HweW6', -2.2161709, -80.8665378);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Santa Elena', 'Ballenita', 'Hotel Ballenita Blue', '🔴 LENTO', '110V 16A', '1.5kW', '24/7', 'Gratuito*', 'https://maps.app.goo.gl/Q7ta5MudHyWNEGVJ7', -2.2107848, -80.8832298);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Santa Elena', 'Ayangue', 'Hotel Kanagua', '🔴 LENTO', '110V 16A', '1.5kW', '24/7', 'Gratuito*', 'https://maps.app.goo.gl/QmC5eMS53tPpmn8e9', -1.9788523, -80.7554958);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Santa Elena', 'Ayangue', 'Hostal El Tamarindo', '🔴 LENTO', '110V 16A', '1.5kW', '24/7', 'Gratuito*', 'https://maps.app.goo.gl/Pr85g1XhPy6SSSF29', -1.9795656, -80.7524336);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Santa Elena', 'Salinas', 'Hotel Villa del Mar', '🟡 NORMAL', '220V 16A Tipo Chino', '3.5kW', '24/7', 'Gratuito*', 'https://maps.app.goo.gl/TtknM4bFAGo6szRNA', -2.2084632, -80.9715101);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Santa Elena', 'Salinas', 'Taller de Soldadura de Ángel', '🟡 NORMAL', '220V 32A Pata Gallina', '7kW', 'Hasta la tarde', 'Gratuito*', 'https://maps.app.goo.gl/Riu3dA3mPnnQteRg6', -2.2306152, -80.9328608);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Santa Elena', 'Salinas', 'Supermaxi — CONDOR CHARGE', '🟢 RÁPIDA', 'CS2', '90kW', '9am-9pm', 'Pago', 'https://maps.app.goo.gl/RrcZQsfS6giYDhQd9', -2.2213099, -80.9448062);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Santa Elena', 'Salinas', 'Hotel Colón', '🟡 NORMAL', 'Tipo 2 Pared', '7kW', '24/7', 'Gratuito*', 'https://maps.app.goo.gl/FUabaPtKtBG6LKiG6', -2.2057114, -80.9643114);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Santa Elena', 'Montañita', 'DHARMA BEACH Hotel', '🟡 NORMAL', 'Tipo 2 Pared', '7kW', '24/7', 'Gratuito*', 'https://maps.app.goo.gl/WQnsw1Zoc76ZbAfL8', -1.8252003, -80.7541495);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'El Oro', 'Huaquillas', 'Hotel Plaza Central', '🟡 NORMAL', '220V 32A Pata Gallina', '7kW', 'Hasta la tarde', 'Gratuito*', 'https://maps.app.goo.gl/5FHMLEzBsgL27yZP9', -3.4798605, -80.2379817);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'El Oro', 'Huaquillas', 'Parqueadero', '🟡 NORMAL', '220V 32A Pata Gallina', '7kW', 'Hasta la tarde', 'Gratuito*', 'https://maps.app.goo.gl/MWzgTLuMQTXmFyTL8', -3.479579, -80.238735);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'El Oro', 'Machala', 'BYD Machala', '🟡 NORMAL', 'Tipo 2 Pared', '7kW', 'Lun-Vie 9am-6pm / Sáb 10am-2pm', 'Pago', 'https://maps.app.goo.gl/nYVuRWzGMaoJ6Hv18', -3.2847, -79.9207);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'El Oro', 'Machala', 'Supermaxi — CONDOR CHARGE', '🟡 NORMAL', 'Tipo 2 + Tipo 1', '7kW', '10am-9pm', 'Pago', 'https://maps.app.goo.gl/wKhvFU2V29xfWZct7', -3.2527295, -79.9752598);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'El Oro', 'Machala', 'Hotel Oro Verde', '🟡 NORMAL', 'Tipo 2 Pared', '7kW', '24/7', 'Gratuito*', 'https://maps.app.goo.gl/S96oL9f6ZdTY4djT7', -3.261906, -79.941094);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'El Oro', 'Machala', 'Punto Carga Comunidad BYD', '⚫ PRIVADO', 'Tipo 2 Pared', '7kW', '24/7 — Agendar', 'Solo miembros BYD', 'RESERVADO - SOLO MIEMBROS BYD', NULL, NULL);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'El Oro', 'Machala', 'Terminal de Machala', '🟡 NORMAL', '220V 32A Pata Gallina', '7kW', '24/7', 'Gratuito*', 'https://maps.app.goo.gl/FdyixvVNiJtfCKG68', -3.2801915, -79.9159431);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'El Oro', 'Santa Rosa', 'Terminal Terrestre Binacional', '🟡 NORMAL', '220V 32A Pata Gallina', '7kW', '24/7', 'Gratuito*', 'https://maps.app.goo.gl/42SUtCGmymPJUq3W7', -3.4476408, -79.9756007);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Manabí', 'Manta', 'Plaza La Quadra', '🟡 NORMAL', 'Tipo 2 Pared', '7kW', '7am-2am', 'Gratuito*', 'https://maps.app.goo.gl/Z6Tq28QH9DKeBzNA6', -0.9456251, -80.7526943);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Manabí', 'Manta', 'Punto Carga Comunidad BYD — Manta Beach', '⚫ PRIVADO', 'Tipo 2 Pared', '7kW', '24/7 — Agendar', 'Solo miembros BYD', 'RESERVADO - SOLO MIEMBROS BYD', NULL, NULL);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Manabí', 'Manta', 'Mall del Pacífico — CONDOR CHARGE', '🟢 RÁPIDA', 'CS2', '90kW', '10am-9pm', 'Pago', 'https://maps.app.goo.gl/f9HhEA8bweKVetAU8', -0.9428104, -80.7322759);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Manabí', 'Ayampe', 'Cerro Lobo', '🟡 NORMAL', 'Tipo 2 Pared', '7kW', '24/7', 'Gratuito*', 'https://maps.app.goo.gl/AmvRehAM8AZT9WwD7', -1.706744, -80.7952305);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Manabí', 'Crucita', 'Punto Carga Comunidad BYD', '⚫ PRIVADO', '220V 32A Pata Gallina', '7kW', '24/7 — Agendar', 'Solo miembros BYD', 'RESERVADO - SOLO MIEMBROS BYD', NULL, NULL);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Manabí', 'Bahía de Caráquez', 'GCDIESEL', '🟡 NORMAL', '220V 32A Pata Gallina', '7kW', 'Tarde', 'Gratuito*', 'https://maps.app.goo.gl/RuXX8trwjPfAFeKc8', -0.6079642, -80.424089);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Manabí', 'Bahía de Caráquez', 'Hotel Saiananda', '🟡 NORMAL', 'Tipo 2 Pared', '7kW', '24/7', 'Gratuito*', 'https://maps.app.goo.gl/xwip4szmqfP3oy9C9', -0.6419566, -80.4103442);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Manabí', 'Bahía de Caráquez', 'Punto Carga Comunidad BYD', '⚫ PRIVADO', '220V 32A Pata Gallina', '7kW', '24/7 — Agendar', 'Solo miembros BYD', 'RESERVADO - SOLO MIEMBROS BYD', NULL, NULL);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Manabí', 'Portoviejo', 'Local Novedades Karen', '🟡 NORMAL', 'Tipo 2 Pared', '7kW', 'Tarde', 'Gratuito*', 'https://goo.gl/maps/Tm6au5KMpAynFFXk9', NULL, NULL);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Manabí', 'Portoviejo', 'Peaje Manta-Portoviejo', '🟡 NORMAL', '220V 32A Pata Gallina', '7kW', '24/7', 'Gratuito*', 'https://maps.app.goo.gl/5K6wcGuAyPUKsrq3A', NULL, NULL);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Manabí', 'Pedernales', 'Playa de Cristal', '🟡 NORMAL', '220V 32A Tipo Normal', '7kW', '24/7', 'Gratuito*', 'https://maps.app.goo.gl/GuAXV7393Pw7SUBQA', 0.2130226, -80.030075);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Manabí', 'Jama', 'Campay — EVINKA CONECT', '🟡 NORMAL', 'Tipo 2 Pared', '7kW', '24/7', 'Pago', 'https://maps.app.goo.gl/T7vburhYeHhtUCZf7', -0.1080472, -80.203186);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Ruta Q-G', 'Quito — Quicentro', 'Quicentro Shopping — EVINKA CONECT', '🟢 RÁPIDA', '60kW CS2', '10am-9pm', 'Pago', 'https://maps.app.goo.gl/mcVxgr7H1MFNeojM6', NULL, NULL, NULL, NULL);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Ruta Q-G', 'Quito — Valle Chillos', 'Supermaxi San Bartolo — CONDOR CHARGE', '🟡 NORMAL', '7kW', '10am-8pm', 'Pago', 'https://maps.app.goo.gl/oStt8aJuTtpXChEC7', NULL, NULL, NULL, NULL);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Ruta Q-G', 'Cerca de Aloag', 'Vulcanizadora Recinto La Virgen', '🟡 NORMAL', '7kW', '24/7', 'Gratuito*', 'https://maps.app.goo.gl/wWewNPJu1orB7fvV6', NULL, NULL, NULL, NULL);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Ruta Q-G', 'Latacunga', 'Restaurante Pepas', '🟡 NORMAL', '7kW', '24/7', 'Gratuito*', 'https://maps.app.goo.gl/534wd5UbkWEZk84E9', NULL, NULL, NULL, NULL);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Ruta Q-G', 'Ambato — Mall de los Andes', 'Mall de los Andes — Electrolinera', '🟢 RÁPIDA', '90kW CS2', '10am-9pm', 'Pago', 'https://maps.app.goo.gl/ZrMmFxQ41KDCWAWS9', NULL, NULL, NULL, NULL);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Ruta Q-G', 'Pelileo', 'Gasolinera PRIMAX Panamericana', '🟢 RÁPIDA', '50kW Multi', '24/7', 'Pago', 'https://maps.app.goo.gl/TxtHtmJr1eAE1btV8', NULL, NULL, NULL, NULL);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Ruta Q-G', 'Pallatanga', 'Auto Diesel Su Amigo', '🟡 NORMAL', '7kW', '24/7', 'Gratuito*', 'https://maps.app.goo.gl/jTq4JKB3KSMLQTdR7', NULL, NULL, NULL, NULL);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Ruta Q-G', 'Bucay', 'Cascada La Poderosa', '🟡 NORMAL', '7kW', 'Hasta tarde', 'Gratuito*', 'https://maps.app.goo.gl/qdR55sDkETPKqKkA9', NULL, NULL, NULL, NULL);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Ruta Q-G', 'Patricia Pilar — Los Ríos', 'Vulcanizadora', '🟡 NORMAL', '7kW', 'Tarde', 'Gratuito*', 'https://goo.gl/maps/NTV8uTJyumMSdgnX8', NULL, NULL, NULL, NULL);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Ruta Q-G', 'Santo Domingo', 'KFC / BYD Bomboli — EVINKA CONECT', '🟢 RÁPIDA', '60kW CS2', '24/7', 'Pago', 'https://maps.app.goo.gl/jRtjsbneP1PCLcXx8', NULL, NULL, NULL, NULL);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Ruta Q-G', 'Guayaquil — Parque Samanes', 'CONDOR CHARGE', '🟢 RÁPIDA', '40kW CS2+CHAdeMO', 'No 6pm-10pm', 'Pago', 'https://maps.app.goo.gl/KCp9jK1nZcG49SGF8', NULL, NULL, NULL, NULL);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Ruta Q-G', 'Guayaquil — Salinas/Ceibos', 'Megamaxi Ceibos — CONDOR CHARGE', '🟢 RÁPIDA', '60kW CS2', '9am-9pm', 'Pago', 'https://maps.app.goo.gl/ezQfESXhXVwWkttk7', NULL, NULL, NULL, NULL);
COMMIT;