-- Script para recrear la tabla con 154 puntos y coordenadas
DROP TABLE IF EXISTS public.charging_points;

CREATE TABLE public.charging_points (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    region TEXT,
    province TEXT,
    city_or_canton TEXT NOT NULL,
    name TEXT NOT NULL,
    speed TEXT,
    charger_type TEXT,
    power TEXT,
    schedule TEXT,
    cost_type TEXT,
    gps_link TEXT,
    lat NUMERIC,
    lng NUMERIC,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
ALTER TABLE public.charging_points ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir lectura pública de puntos de carga" ON public.charging_points FOR SELECT USING (true);
  
BEGIN;
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'PROVINCIA', 'CANTÓN / CIUDAD', 'NOMBRE DEL PUNTO', 'VELOCIDAD', 'TIPO DE CARGADOR', 'POTENCIA', 'HORARIO', 'COSTO', 'ENLACE GPS', NULL, NULL);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Esmeraldas', 'La Unión', 'Lubricentro Brito', '🟡 NORMAL', '220V 32A Pata Gallina', '7kW', '24/7', 'Gratuito*', 'https://maps.app.goo.gl/F2TgyEFGJw1hRH716', NULL, NULL);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Esmeraldas', 'La Concordia', 'Ultra NRG Gasolinera Multiservicios', '🟡 NORMAL', 'Tipo 2 Pared', '7kW', '24/7', 'Consultar', 'https://maps.app.goo.gl/utE8PqRRsRtekjDk8', -0.0148146, -79.3826533);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Esmeraldas', 'San Mateo', 'Gasolinera P&S San Mateo', '🟡 NORMAL', '220V 32A Pata Gallina', '7kW', '24/7', 'Gratuito*', 'https://maps.app.goo.gl/kcio9fEoDLdSW3Xh8', 0.8769098, -79.6376649);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Esmeraldas', 'Tonsupa', 'Castelnuovo', '🟡 NORMAL', '220V 32A Pata Gallina', '7kW', 'Tarde', 'Gratuito*', 'https://maps.app.goo.gl/qAU3nMLdvvS6VLX48', 0.8818976, -79.8352511);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Esmeraldas', 'Salima', 'Gasolinera PetroRíos San Luis', '🟡 NORMAL', '220V 32A Pata Gallina', '7kW', '24/7', 'Gratuito*', 'https://maps.app.goo.gl/cfFQ58fbrtWs4LgT7', NULL, NULL);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Esmeraldas', 'Atacames', 'Taller Don Milton', '🟡 NORMAL', '220V 32A Pata Gallina', '7kW', 'Tarde', 'Gratuito*', 'https://maps.app.goo.gl/ANeMBL7UeQ51kqJv5', 0.8685172, -79.8553785);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Santo Domingo', 'Santo Domingo', 'KFC Santo Domingo — EVINKA CONECT', '🟢 RÁPIDA', 'Tipo 2 + CS2', '7kW / 60kW', '24/7', 'Pago', 'https://maps.app.goo.gl/jRtjsbneP1PCLcXx8', -0.2627128, -79.114653);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Santo Domingo', 'Santo Domingo', 'BYD Bomboli Shopping — EVINKA CONECT', '🟢 RÁPIDA', 'Tipo 2 + CS2', '7kW / 60kW', 'Lun-Dom 10am-9pm', 'Pago', 'https://maps.app.goo.gl/yDGX4RRYnq42dWWA7', -0.2536396, -79.2212342);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Santo Domingo', 'Santo Domingo', 'BYD Bomboli Shopping — CONDOR CHARGE', '🟢 RÁPIDA', 'Tipo 2 + CS2', '7kW / 60kW', 'Lun-Dom 10am-9pm', 'Pago', 'https://maps.app.goo.gl/yDGX4RRYnq42dWWA7', -0.2536396, -79.2212342);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Santo Domingo', 'Santo Domingo', 'Club del Campo Hotel & Convenciones', '🟡 NORMAL', '220V 32A Pata Gallina', '7kW', 'Tarde', 'Gratuito*', 'https://maps.app.goo.gl/JsukMbBhpZDZutfa6', -0.2339237, -79.1345977);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Santo Domingo', 'Santo Domingo', 'Hostería Los Colorados', '🟡 NORMAL', 'Tipo 2 Pared', '7kW', '24/7', 'Gratuito*', 'https://maps.app.goo.gl/Bui7YmsbNHU37qb58', -0.2730613, -79.0872073);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Santo Domingo', 'Cerca de Aloag', 'Vulcanizadora Recinto La Virgen', '🟡 NORMAL', '220V 32A Pata Gallina', '7kW', '24/7', 'Gratuito*', 'https://maps.app.goo.gl/wWewNPJu1orB7fvV6', -0.4432349, -78.7547383);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Santo Domingo', 'Luz de América', 'Frente al Comercial Ponce', '🟡 NORMAL', '220V 32A Pata Gallina', '7kW', 'Tarde', 'Gratuito*', 'https://maps.app.goo.gl/dToQjP5YywexHsvs7', NULL, NULL);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Los Ríos', 'Patricia Pilar', 'Vulcanizadora', '🟡 NORMAL', '220V 32A Pata Gallina', '7kW', 'Tarde', 'Gratuito*', 'https://goo.gl/maps/NTV8uTJyumMSdgnX8', -0.568778, -79.370833);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Los Ríos', 'Babahoyo', 'Punto de Carga Comunidad BYD — Pueblo Nuevo', '🟡 NORMAL', 'Tipo 2 Pared', '7kW', '24/7 — Agendar', 'Solo miembros BYD', 'RESERVADO - SOLO MIEMBROS BYD', NULL, NULL);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Guayas', 'Guayaquil', 'BYD Juan Tanga Marengo', '🟢 RÁPIDA', 'Tipo 2 + CS2', '7kW / 60kW', 'Lun-Vie 9am-6pm / Sáb 10am-2pm', 'Pago', 'https://maps.app.goo.gl/1BDtbuHnVYeURAhW7', NULL, NULL);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Guayas', 'Guayaquil', 'BYD Américas', '🟡 NORMAL', 'Tipo 2 Pared', '7kW', 'Lun-Vie 9am-6pm / Sáb 10am-2pm', 'Pago', 'https://maps.app.goo.gl/h4JYzTDghEkhpUUq6', -2.1428356, -79.8843857);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Guayas', 'Guayaquil', 'Mall del Norte', '🟡 NORMAL', 'Tipo 1 + Tipo 2', '7kW', 'Hasta 9pm', 'Gratuito*', 'https://maps.app.goo.gl/VZKWDhXmuSWNsUKt7', NULL, NULL);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Guayas', 'Guayaquil', 'City Mall', '🟡 NORMAL', 'Tipo 1 Pared', '7kW', 'Hasta 9pm', 'Gratuito*', 'https://maps.app.goo.gl/QLgm9YUowbwG1fpQ7', NULL, NULL);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Guayas', 'Guayaquil', 'Parque Samanes — CONDOR CHARGE', '🟢 RÁPIDA', 'CS2 + CHAdeMO + Tipo 2', '40kW / 40kW / 7kW', 'Abierto excepto 6pm-10pm', 'Pago', 'https://maps.app.goo.gl/KCp9jK1nZcG49SGF8', -2.1024911, -79.8897837);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Guayas', 'Guayaquil', 'Megamaxi Ceibos — CONDOR CHARGE', '🟢 RÁPIDA', 'CS2 — PRÓXIMAMENTE', '60kW', '9am-9pm', 'Pago', 'https://maps.app.goo.gl/ezQfESXhXVwWkttk7', -2.1735755, -79.9423254);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Guayas', 'Guayaquil Vía la Costa', 'Primax Puerto Azul', '🟡 NORMAL', 'Tipo 1 Pared', '7kW', '24/7', 'Gratuito*', 'https://maps.app.goo.gl/6rCv1ZnmQ7NwcUmr8', -2.187429, -79.9741114);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Guayas', 'Guayaquil Vía la Costa', 'Burger King — EVINKA CONECT', '🟡 NORMAL', 'Tipo 2 Pared', '7kW', 'Lun-Dom 10am-1am', 'Pago', 'https://maps.app.goo.gl/iJerLjoe8xr6BrZQ8', -2.1822202, -79.9819071);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Guayas', 'Durán', 'Punto Carga Comunidad BYD — Panorama', '⚫ PRIVADO', 'Tipo 2 Pared', '7kW', '6am-11pm — Agendar', 'Solo miembros BYD', 'RESERVADO - SOLO MIEMBROS BYD', NULL, NULL);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Guayas', 'Samborondón', 'Punto Carga Comunidad BYD — Ciudad Celeste', '⚫ PRIVADO', 'Tipo 2 Pared', '7kW', '24/7 — Agendar', 'Solo miembros BYD', 'RESERVADO - SOLO MIEMBROS BYD', NULL, NULL);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Guayas', 'Samborondón', 'Plaza Lagos', '🟡 NORMAL', 'Tipo 2 Pared', '7kW', '8am-11pm', 'Gratuito*', 'https://maps.app.goo.gl/ZzqYfXX2Dj2dnfpq8', -2.1262174, -79.8641962);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Guayas', 'Samborondón', 'Village', '🟡 NORMAL', 'Tipo 1 Pared (Adaptador)', '3.5kW', '10am-9pm', 'Gratuito*', 'https://maps.app.goo.gl/YdKxtRXf4Sz7qHzR6', -2.1034457, -79.9266375);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Guayas', 'Samborondón', 'Marbol Plaza', '🟡 NORMAL', 'Tipo 2 Pared', '7kW', '8am-10pm', 'Gratuito*', 'https://maps.app.goo.gl/ZzqYfXX2Dj2dnfpq8', -2.1262174, -79.8641962);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Guayas', 'Samborondón', 'Parque La Paz Aurora', '🟡 NORMAL', 'Tipo 2 Pared', '3.5kW', '24/7', 'Gratuito*', 'https://maps.app.goo.gl/S8JCDE5z7poBjfSe8', -2.0508396, -79.9044505);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Guayas', 'Playas Villamil', 'Punto Carga Comunidad BYD', '⚫ PRIVADO', 'Tipo 2 Pared', '7kW', '24/7 — Agendar', 'Solo miembros BYD', 'RESERVADO - SOLO MIEMBROS BYD', NULL, NULL);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Guayas', 'Playas Villamil', 'La Costa Club de Campo', '🟡 NORMAL', 'Tipo 2 Pared', '7kW', '8am-5pm', 'Gratuito*', 'https://maps.app.goo.gl/WUT2zb4CSkAtiee2A', -2.2724914, -80.1556681);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Guayas', 'Playas Villamil', 'Hotel Presidente Premium', '🟡 NORMAL', '220V Tipo Chino + Pata Gallina', '3.5-7kW', '24/7', 'Gratuito*', 'https://maps.app.goo.gl/pFDGh8JBzmTAe2nn9', -2.6600364, -80.3767978);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Guayas', 'Playas Villamil', 'Hotel Luna Azzul', '🟡 NORMAL', '220V 16A-32A', '3.5-7kW', '24/7', 'Gratuito*', 'https://maps.app.goo.gl/fsoWacmttjkHzHSa8', -2.6417404, -80.389927);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Chimborazo', 'Bucay', 'Cascada La Poderosa — Vía Chillanes', '🟡 NORMAL', '220V 32A Pata Gallina', '7kW', 'Hasta la tarde', 'Gratuito*', 'https://maps.app.goo.gl/qdR55sDkETPKqKkA9', -2.1312003, -79.1181197);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Guayas', 'Naranjal', 'Punto Carga Comunidad BYD', '⚫ PRIVADO', 'Tipo 2 Pared', '7kW', '24/7 — Agendar', 'Solo miembros BYD', 'RESERVADO - SOLO MIEMBROS BYD', NULL, NULL);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Santa Elena', 'Santa Elena', 'Punto Carga Comunidad BYD', '⚫ PRIVADO', 'Tipo 2 Pared', '7kW', '24/7 — Agendar', 'Solo miembros BYD', 'RESERVADO - SOLO MIEMBROS BYD', NULL, NULL);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Santa Elena', 'Santa Elena', 'Vulcanizadora junto a Mago Fast Food', '🟡 NORMAL', '220V 32A Pata Gallina', '7kW', 'Hasta la tarde', 'Gratuito*', 'https://maps.app.goo.gl/wmncQ8aeED4TGH5bA', -2.2312822, -80.8673098);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Santa Elena', 'Santa Elena', 'Terminal de Santa Elena', '🟡 NORMAL', 'Tipo 2 Pared', '7kW', '24/7', 'Gratuito*', 'https://maps.app.goo.gl/wHREtfHZzsL6HweW6', -2.2161709, -80.8691127);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Santa Elena', 'Ballenita', 'Hotel Ballenita Blue', '🔴 LENTO', '110V 16A', '1.5kW', '24/7', 'Gratuito*', 'https://maps.app.goo.gl/Q7ta5MudHyWNEGVJ7', -2.2097994, -80.8809017);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Santa Elena', 'Ayangue', 'Hotel Kanagua', '🔴 LENTO', '110V 16A', '1.5kW', '24/7', 'Gratuito*', 'https://maps.app.goo.gl/QmC5eMS53tPpmn8e9', -1.9788989, -80.7554866);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Santa Elena', 'Ayangue', 'Hostal El Tamarindo', '🔴 LENTO', '110V 16A', '1.5kW', '24/7', 'Gratuito*', 'https://maps.app.goo.gl/Pr85g1XhPy6SSSF29', -1.9795656, -80.7524336);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Santa Elena', 'Salinas', 'Hotel Villa del Mar', '🟡 NORMAL', '220V 16A Tipo Chino', '3.5kW', '24/7', 'Gratuito*', 'https://maps.app.goo.gl/TtknM4bFAGo6szRNA', -2.2084632, -80.974085);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Santa Elena', 'Salinas', 'Taller de Soldadura de Ángel', '🟡 NORMAL', '220V 32A Pata Gallina', '7kW', 'Hasta la tarde', 'Gratuito*', 'https://maps.app.goo.gl/Riu3dA3mPnnQteRg6', -2.2306152, -80.9354357);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Santa Elena', 'Salinas', 'Supermaxi — CONDOR CHARGE', '🟢 RÁPIDA', 'CS2', '90kW', '9am-9pm', 'Pago', 'https://maps.app.goo.gl/RrcZQsfS6giYDhQd9', -2.2213099, -80.9473811);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Santa Elena', 'Salinas', 'Hotel Colón', '🟡 NORMAL', 'Tipo 2 Pared', '7kW', '24/7', 'Gratuito*', 'https://maps.app.goo.gl/FUabaPtKtBG6LKiG6', -2.2057114, -80.9643114);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Santa Elena', 'Montañita', 'DHARMA BEACH Hotel', '🟡 NORMAL', 'Tipo 2 Pared', '7kW', '24/7', 'Gratuito*', 'https://maps.app.goo.gl/WQnsw1Zoc76ZbAfL8', -1.8252003, -80.7541495);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'El Oro', 'Huaquillas', 'Hotel Plaza Central', '🟡 NORMAL', '220V 32A Pata Gallina', '7kW', 'Hasta la tarde', 'Gratuito*', 'https://maps.app.goo.gl/5FHMLEzBsgL27yZP9', -3.4798605, -80.2379817);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'El Oro', 'Huaquillas', 'Parqueadero', '🟡 NORMAL', '220V 32A Pata Gallina', '7kW', 'Hasta la tarde', 'Gratuito*', 'https://maps.app.goo.gl/MWzgTLuMQTXmFyTL8', -3.4798716, -80.2388266);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'El Oro', 'Machala', 'BYD Machala', '🟡 NORMAL', 'Tipo 2 Pared', '7kW', 'Lun-Vie 9am-6pm / Sáb 10am-2pm', 'Pago', 'https://maps.app.goo.gl/nYVuRWzGMaoJ6Hv18', -3.2847, -79.9232749);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'El Oro', 'Machala', 'Supermaxi — CONDOR CHARGE', '🟡 NORMAL', 'Tipo 2 + Tipo 1', '7kW', '10am-9pm', 'Pago', 'https://maps.app.goo.gl/wKhvFU2V29xfWZct7', -3.2529507, -80.0113088);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'El Oro', 'Machala', 'Hotel Oro Verde', '🟡 NORMAL', 'Tipo 2 Pared', '7kW', '24/7', 'Gratuito*', 'https://maps.app.goo.gl/S96oL9f6ZdTY4djT7', -3.2619006, -79.9436743);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'El Oro', 'Machala', 'Punto Carga Comunidad BYD', '⚫ PRIVADO', 'Tipo 2 Pared', '7kW', '24/7 — Agendar', 'Solo miembros BYD', 'RESERVADO - SOLO MIEMBROS BYD', NULL, NULL);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'El Oro', 'Machala', 'Terminal de Machala', '🟡 NORMAL', '220V 32A Pata Gallina', '7kW', '24/7', 'Gratuito*', 'https://maps.app.goo.gl/FdyixvVNiJtfCKG68', -3.2801915, -79.918518);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'El Oro', 'Santa Rosa', 'Terminal Terrestre Binacional', '🟡 NORMAL', '220V 32A Pata Gallina', '7kW', '24/7', 'Gratuito*', 'https://maps.app.goo.gl/42SUtCGmymPJUq3W7', -3.4476408, -79.9781756);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Manabí', 'Manta', 'Plaza La Quadra', '🟡 NORMAL', 'Tipo 2 Pared', '7kW', '7am-2am', 'Gratuito*', 'https://maps.app.goo.gl/Z6Tq28QH9DKeBzNA6', -0.9456396, -81.9063377);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Manabí', 'Manta', 'Punto Carga Comunidad BYD — Manta Beach', '⚫ PRIVADO', 'Tipo 2 Pared', '7kW', '24/7 — Agendar', 'Solo miembros BYD', 'RESERVADO - SOLO MIEMBROS BYD', NULL, NULL);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Manabí', 'Manta', 'Mall del Pacífico — CONDOR CHARGE', '🟢 RÁPIDA', 'CS2', '90kW', '10am-9pm', 'Pago', 'https://maps.app.goo.gl/f9HhEA8bweKVetAU8', -0.9428104, -80.7348508);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Manabí', 'Ayampe', 'Cerro Lobo', '🟡 NORMAL', 'Tipo 2 Pared', '7kW', '24/7', 'Gratuito*', 'https://maps.app.goo.gl/AmvRehAM8AZT9WwD7', -1.706744, -80.7978054);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Manabí', 'Crucita', 'Punto Carga Comunidad BYD', '⚫ PRIVADO', '220V 32A Pata Gallina', '7kW', '24/7 — Agendar', 'Solo miembros BYD', 'RESERVADO - SOLO MIEMBROS BYD', NULL, NULL);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Manabí', 'Bahía de Caráquez', 'GCDIESEL', '🟡 NORMAL', '220V 32A Pata Gallina', '7kW', 'Tarde', 'Gratuito*', 'https://maps.app.goo.gl/RuXX8trwjPfAFeKc8', -0.6079642, -80.4266639);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Manabí', 'Bahía de Caráquez', 'Hotel Saiananda', '🟡 NORMAL', 'Tipo 2 Pared', '7kW', '24/7', 'Gratuito*', 'https://maps.app.goo.gl/xwip4szmqfP3oy9C9', -0.6420287, -80.4105016);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Manabí', 'Bahía de Caráquez', 'Punto Carga Comunidad BYD', '⚫ PRIVADO', '220V 32A Pata Gallina', '7kW', '24/7 — Agendar', 'Solo miembros BYD', 'RESERVADO - SOLO MIEMBROS BYD', NULL, NULL);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Manabí', 'Portoviejo', 'Local Novedades Karen', '🟡 NORMAL', 'Tipo 2 Pared', '7kW', 'Tarde', 'Gratuito*', 'https://goo.gl/maps/Tm6au5KMpAynFFXk9', -1.057087, -80.455617);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Manabí', 'Portoviejo', 'Peaje Manta-Portoviejo', '🟡 NORMAL', '220V 32A Pata Gallina', '7kW', '24/7', 'Gratuito*', 'https://maps.app.goo.gl/5K6wcGuAyPUKsrq3A', NULL, NULL);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Manabí', 'Pedernales', 'Playa de Cristal', '🟡 NORMAL', '220V 32A Tipo Normal', '7kW', '24/7', 'Gratuito*', 'https://maps.app.goo.gl/GuAXV7393Pw7SUBQA', 0.2130226, -80.0326499);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Costa', 'Manabí', 'Jama', 'Campay — EVINKA CONECT', '🟡 NORMAL', 'Tipo 2 Pared', '7kW', '24/7', 'Pago', 'https://maps.app.goo.gl/T7vburhYeHhtUCZf7', -0.1080472, -80.2057609);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Sierra', 'PROVINCIA', 'CANTÓN / CIUDAD', 'NOMBRE DEL PUNTO', 'VELOCIDAD', 'TIPO DE CARGADOR', 'POTENCIA', 'HORARIO', 'COSTO', 'ENLACE GPS', NULL, NULL);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Sierra', 'Pichincha', 'Puerto Quito', 'The River House Lodge — EVINKA CONECT', '🟡 NORMAL', 'Tipo 2 Pared', '7kW', '24/7', 'Pago', 'https://maps.app.goo.gl/HkjQ5GER9DoaWz1c9', 0.1124661, -79.2321931);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Sierra', 'Pichincha', 'Puerto Quito', 'Restaurante Alado Toñito', '🟡 NORMAL', '220V 32A Pata Gallina', '7kW', 'Tarde', 'Gratuito*', 'https://maps.app.goo.gl/1dUBHweGtp5sHATY9', 0.1239437, -79.2370394);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Sierra', 'Pichincha', 'Pedro Vicente Maldonado', 'Hotel Balcón Alcalá', '🟡 NORMAL', 'Tipo 2 Pared', '7kW', '24/7', 'Gratuito*', 'https://maps.app.goo.gl/SGs3sQJCvmrD12C19', 0.0985133, -79.1180121);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Sierra', 'Pichincha', 'Tabacundo', 'Punto Carga Comunidad BYD', '⚫ PRIVADO', 'Tipo 2 Pared', '7kW', '7am-5pm — Agendar', 'Solo miembros BYD', 'RESERVADO - SOLO MIEMBROS BYD', NULL, NULL);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Sierra', 'Pichincha', 'Tabacundo', 'Vulcanizadora Q.L', '🟡 NORMAL', '220V 32A Pata Gallina', '7kW', '24/7', 'Gratuito*', 'https://maps.app.goo.gl/a2g7N8d3LxeYj4fXA', 0.0448331, -78.2287878);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Sierra', 'Pichincha', 'Quito', 'Supermaxi Plaza Norte — CONDOR CHARGE', '🟡 NORMAL', 'Tipo 2 Pared', '7kW', '9:30am-8pm', 'Pago', 'https://maps.app.goo.gl/A5oGAKkD7JJ25C8w8', -0.1313664, -78.4844114);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Sierra', 'Pichincha', 'Quito', 'Studio 3 Peluquería', '🟡 NORMAL', 'Tipo 2 Pared', '7kW', '8am-7pm', 'Gratuito*', 'https://maps.app.goo.gl/QHm6Dd6VyAy4yqHd9', -0.1285854, -78.4997935);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Sierra', 'Pichincha', 'Quito', 'Centro Comercial Montúfar', '🟡 NORMAL', 'Tipo 1 (Adaptador)', '7kW', '9am-5pm', 'Gratuito*', 'https://maps.app.goo.gl/evx2pQhJHsSw3T9', NULL, NULL);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Sierra', 'Pichincha', 'Quito', 'Alado del Citimed Clínica', '🟡 NORMAL', 'Tipo 2 Pared', '7kW', 'Tarde', 'Gratuito*', 'https://maps.app.goo.gl/NurGeP7HE41Am2SS9', -0.1833213, -78.5051543);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Sierra', 'Pichincha', 'Quito', 'Supermaxi Granda Centeno — CONDOR CHARGE', '🟡 NORMAL', 'Tipo 2 Pared', '7kW', '9:30am-8:30pm', 'Pago', 'https://maps.app.goo.gl/nFDYEMabNSLhYw9C9', -0.171005, -78.4909173);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Sierra', 'Pichincha', 'Quito', 'Megamaxi 6 de Diciembre — CONDOR CHARGE', '🟢 RÁPIDA', 'CS2 + CHAdeMO + CS1 + Tipo 2', '90kW', '10am-9pm', 'Pago', 'https://maps.app.goo.gl/npDrizD8xiTej2XN6', -0.171871, -78.4797735);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Sierra', 'Pichincha', 'Quito', 'DHL Express Punto de Venta', '🟡 NORMAL', 'Tipo 2 Pared', '7kW', '8:30am-6:30pm', 'Gratuito*', 'https://maps.app.goo.gl/Cnosa3pKZGDR57uQ6', -0.121224, -78.4718466);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Sierra', 'Pichincha', 'Quito', 'Mall del Jardín', '🟡 NORMAL', 'Tipo 1 (Adaptador)', '7kW', '10am-9pm', 'Gratuito*', 'https://maps.app.goo.gl/vJ7ENEBQeBchkK6f6', -0.1893797, -78.4903792);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Sierra', 'Pichincha', 'Quito', 'Terminal Carcelén', '🟡 NORMAL', 'Tipo 1 (Adaptador)', '7kW', '24/7', 'Gratuito*', 'https://maps.app.goo.gl/frFzJiaPasXGpB7V8', -0.0999519, -78.4730673);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Sierra', 'Pichincha', 'Quito', 'BYD Sangolquí', '🟡 NORMAL', 'Tipo 2 Pared', '7kW', 'Lun-Vie 9am-6pm / Sáb 10am-2pm', 'Pago', 'https://maps.app.goo.gl/WM33cxCpS1Ai3MNF9', -0.3455378, -78.4509215);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Sierra', 'Pichincha', 'Quito', 'PILLAJO CORP. Electrolinera', '🟢 RÁPIDA', 'CS2', '60kW', 'Lun-Vie 7am-5:30pm — Con agendamiento', 'Pago', 'https://maps.app.goo.gl/9fbiJLnNfiAiMHzw9', -0.3431646, -78.4793488);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Sierra', 'Pichincha', 'Quito', 'Quicentro Shopping — EVINKA CONECT', '🟢 RÁPIDA', 'CS2 + Tipo 2', '60kW / 7kW', 'Lun-Dom 10am-9pm', 'Pago', 'https://maps.app.goo.gl/mcVxgr7H1MFNeojM6', -0.1762888, -78.4817643);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Sierra', 'Pichincha', 'Quito — Cumbayá', 'Burger King Cumbayá — EVINKA CONECT', '🟡 NORMAL', 'Tipo 2 Pared', '7kW', 'Lun-Dom 7am-1am', 'Pago', 'https://maps.app.goo.gl/PH61tAtdWbZDFVds9', -0.1954441, -78.4475184);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Sierra', 'Pichincha', 'Quito — Cumbayá', 'Scala Shopping Mall', '🟡 NORMAL', 'Tipo 2 Pared', '7kW', '10am-8:30pm', 'Gratuito*', 'https://maps.app.goo.gl/MeiyF934nWKLdFgV6', -0.2019853, -78.4610634);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Sierra', 'Pichincha', 'Quito — Cumbayá', 'La Tejeadora', '🟡 NORMAL', 'Tipo 1 (Adaptador)', '7kW', '6am-2am', 'Gratuito*', 'https://maps.app.goo.gl/D9tzR69iJeDHQTDN8', -0.2060792, -78.4281647);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Sierra', 'Pichincha', 'Quito — Cumbayá', 'BYD Cumbayá', '🟡 NORMAL', 'Tipo 2 Pared', '7kW', 'Lun-Vie 9am-6pm / Sáb 10am-2pm', 'Pago', 'https://maps.app.goo.gl/JPvgRLofciTfB9pd8', -0.1978221, -78.4391145);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Sierra', 'Pichincha', 'Quito — Valle Chillos', 'BYD en Valle de los Chillos — San Rafael', '🟡 NORMAL', 'Tipo 2 Pared', '7kW', 'Lun-Vie 9am-6pm / Sáb 10am-2pm', 'Pago', 'https://maps.app.goo.gl/yvfh1zyr9n6cPDBo9', -0.2023123, -78.6312406);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Sierra', 'Pichincha', 'Quito — Valle Chillos', 'Burger King Valle Chillos — EVINKA CONECT', '🟡 NORMAL', 'Tipo 2 Pared', '7kW', 'Lun-Dom 7am-1am', 'Pago', 'https://maps.app.goo.gl/Frn53k6kcBhNE7mi9', -0.294309, -78.45129);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Sierra', 'Pichincha', 'Quito', 'BYD CORASA', '🟡 NORMAL', 'Tipo 2 Pared', '7kW', 'Lun-Vie 9am-6pm / Sáb 10am-2pm', 'Pago', 'https://maps.app.goo.gl/EARggkJxBzpKaoVMA', -0.1301301, -78.4836086);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Sierra', 'Pichincha', 'Quito', 'Paseo San Francisco — CONDOR CHARGE', '🟡 NORMAL', 'Tipo 2 Pared', '7kW', '10am-8pm', 'Pago', 'https://maps.app.goo.gl/szLFWCPYgnoghFid9', -0.1991495, -78.4391529);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Sierra', 'Pichincha', 'Quito — Valle Chillos', 'Supermaxi San Bartolo — CONDOR CHARGE', '🟡 NORMAL', 'Tipo 2 Pared', '7kW', '10am-8pm', 'Pago', 'https://maps.app.goo.gl/oStt8aJuTtpXChEC7', -0.2736051, -78.5479471);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Sierra', 'Pichincha', 'Quito', 'Plaza Marquesina', '🟡 NORMAL', 'Tipo 2 Pared', '7kW', 'Tarde', 'Gratuito*', 'https://maps.app.goo.gl/UoeHfWeAxjWCACLc7', NULL, NULL);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Sierra', 'Pichincha', 'Quito — Tumbaco', 'Supermaxi La Cerámica', '🟡 NORMAL', 'Tipo 2 Pared', '7kW', '9:30am-8:30pm', 'Pago', 'https://maps.app.goo.gl/mszkUSQAUQa8apzU6', -0.2153406, -78.411815);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Sierra', 'Pichincha', 'Quito', 'Mall El Jardín', '🟡 NORMAL', 'Tipo 1 (Adaptador)', '7kW', '10am-8:30pm', 'Gratuito*', 'https://maps.app.goo.gl/FsYWG9qdjsNGC7AN9', -0.1893797, -78.4903792);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Sierra', 'Pichincha', 'Quito', 'Centro Comercial Iñaquito CCI', '🟡 NORMAL', 'Tipo 2 Pared', '7kW', '9:30am-9pm', 'Gratuito*', 'https://maps.app.goo.gl/7hZyjApFQrdTxcQ56', -0.1769743, -78.4853864);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Sierra', 'Pichincha', 'Quito', 'Estacionamiento Carolina 1 — CONDOR CHARGE', '🟡 NORMAL', 'Tipo 2 Pared', '7kW', '24/7', 'Pago', 'https://maps.app.goo.gl/MEDbS7YUeb8moYcZ7', -0.1797898, -78.5115573);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Sierra', 'Imbabura', 'Otavalo', 'Hostería Cabañas del Lago', '🟡 NORMAL', 'Tipo 2 Pared', '7kW', '24/7', 'Gratuito*', 'https://maps.app.goo.gl/iR1Ch5KUzzu5n9tz7', 0.2104164, -78.2108468);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Sierra', 'Imbabura', 'Cerca de Ambuquí', 'Punto Carga Comunidad BYD — Peaje Ambuquí', '⚫ PRIVADO', 'Tipo 2 Pared', '7kW', '7am-8pm — Agendar', 'Solo miembros BYD', 'RESERVADO - SOLO MIEMBROS BYD', NULL, NULL);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Sierra', 'Imbabura', 'Ibarra', 'Punto Carga Comunidad BYD — Otavalo/Ibarra', '⚫ PRIVADO', '220V 32A Pata Gallina', '7kW', '24/7 — Agendar', 'Solo miembros BYD', 'RESERVADO - SOLO MIEMBROS BYD', NULL, NULL);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Sierra', 'Imbabura', 'Ibarra', 'BYD Ibarra', '🟡 NORMAL', 'Tipo 2 Pared', '7kW', 'Lun-Vie 9am-6pm / Sáb 10am-2pm', 'Pago', 'https://maps.app.goo.gl/wvaaUD7rC4YozAhL8', 0.3418853, -78.1432447);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Sierra', 'Imbabura', 'Ibarra', 'Hostería El Prado — EVINKA CONECT', '🟡 NORMAL', 'Tipo 2 Pared', '7kW', '24/7', 'Pago', 'https://maps.app.goo.gl/MwVBD1e3k33xUB1j6', 0.3647635, -78.1145881);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Sierra', 'Imbabura', 'Ibarra', 'Punto Carga Comunidad BYD — Ibarra 2', '⚫ PRIVADO', 'Tipo 2 Pared', '7kW', '24/7 — Agendar', 'Solo miembros BYD', 'RESERVADO - SOLO MIEMBROS BYD', NULL, NULL);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Sierra', 'Carchi', 'Tulcán', 'Casa familiar cerca Coliseo — Garaje seguro', '🟡 NORMAL', '220V 32A Pata Gallina', '7kW', '24/7', 'Gratuito*', 'https://maps.app.goo.gl/aw48AXdEA6wUYJ2UA', 0.8238254, -77.7160476);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Sierra', 'Cotopaxi', 'Latacunga', 'Restaurante Pepas', '🟡 NORMAL', 'Tipo 2 Pared', '7kW', '24/7', 'Gratuito*', 'https://maps.app.goo.gl/534wd5UbkWEZk84E9', -0.9227482, -78.6226413);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Sierra', 'Cotopaxi', 'Latacunga', 'Maltería Plaza — KIA', '🟡 NORMAL', 'Tipo 1 Pared', '7kW', '10am-8pm', 'Gratuito*', 'https://maps.app.goo.gl/J7GFveKvwZzFPD6H7', -0.9264817, -78.6267202);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Sierra', 'Tungurahua', 'Ambato', 'Punto Carga Comunidad BYD', '⚫ PRIVADO', 'Tipo 2 Pared', '7kW', '24/7 — Agendar', 'Solo miembros BYD', 'RESERVADO - SOLO MIEMBROS BYD', NULL, NULL);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Sierra', 'Tungurahua', 'Ambato', 'Mall de los Andes — Electrolinera', '🟢 RÁPIDA', 'CS2', '90kW', '10am-9pm', 'Pago', 'https://maps.app.goo.gl/ZrMmFxQ41KDCWAWS9', -1.2652797, -78.6281705);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Sierra', 'Tungurahua', 'Pillaro — Cerca Ambato', 'Tomacorriente Tipo Chino', '🔴 LENTO', '220V 16A Tipo Chino', '3.5kW', 'Tarde', 'Gratuito*', 'https://maps.app.goo.gl/pjYWDYghjavRoHfS9', -1.170751, -78.545616);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Sierra', 'Tungurahua', 'Ambato', 'Supermaxi Ficoa — CONDOR CHARGE', '🟡 NORMAL', 'Tipo GBT Pared', '7kW', '9:30am-8:30pm', 'Pago', 'https://maps.app.goo.gl/dw8LmNyMyqK4SJQz9', -1.2355179, -78.6355453);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Sierra', 'Tungurahua', 'Pelileo', 'Gasolinera PRIMAX Panamericana — Electrolinera', '🟢 RÁPIDA', 'CS1 + CS2 + CHAdeMO + Mennekes', '50kW', '24/7', 'Pago', 'https://maps.app.goo.gl/TxtHtmJr1eAE1btV8', -1.3263946, -78.5442206);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Sierra', 'Tungurahua', 'Baños', 'Punto Carga Comunidad BYD — Centro Baños', '⚫ PRIVADO', '220V 32A Pata Gallina', '7kW', '24/7 — Agendar', 'Solo miembros BYD', 'RESERVADO - SOLO MIEMBROS BYD', NULL, NULL);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Sierra', 'Tungurahua', 'Baños', 'Samarí Spa Resort', '🟡 NORMAL', 'Tipo 2 Pared', '7kW', '24/7', 'Gratuito*', 'https://maps.app.goo.gl/eEqEhDuHmsqdGzCr6', -1.3953649, -78.4106707);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Sierra', 'Tungurahua', 'Baños', 'Hotel Spa Miramelindo', '🟡 NORMAL', 'Tipo 2 Pared', '7kW', '24/7', 'Gratuito*', 'https://maps.app.goo.gl/3RiTcVX5p5pWcc9q9', -1.40019, -78.3003427);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Sierra', 'Chimborazo', 'Riobamba', 'Megamaxi Multiplaza — CONDOR CHARGE (Próximamente)', '🟢 RÁPIDA', 'CS2 — PRÓXIMAMENTE', '60kW', '9am-9pm', 'Pago', 'https://maps.app.goo.gl/y9evv1VYhQw8RDaMA', -1.6562277, -78.6663017);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Sierra', 'Chimborazo', 'Riobamba', 'Hotel La Colina', '🟡 NORMAL', '220V 32A Pata Gallina', '7kW', '24/7', 'Gratuito*', 'https://maps.app.goo.gl/qUTkSRaBtMcpyoDn6', -1.6652625, -78.6766032);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Sierra', 'Chimborazo', 'Cerca Riobamba', 'Hostería Andaluza', '🟡 NORMAL', 'Tipo 2 Pared', '7kW', '24/7', 'Gratuito*', 'https://maps.app.goo.gl/2QURzJfjjmJpywZT8', -1.5383734, -78.7352718);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Sierra', 'Chimborazo', 'Riobamba', 'BYD Riobamba', '🟡 NORMAL', 'Tipo 2 Pared', '7kW', 'Lun-Vie 9am-6pm / Sáb 10am-2pm', 'Pago', 'https://maps.app.goo.gl/4NBjmt4Nd2K9uSGLA', -1.6422859, -78.6787329);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Sierra', 'Chimborazo', 'Riobamba', 'Punto Carga Comunidad BYD', '⚫ PRIVADO', 'Tipo 2 Pared', '7kW', '8am-11pm — Agendar', 'Solo miembros BYD', 'RESERVADO - SOLO MIEMBROS BYD', NULL, NULL);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Sierra', 'Chimborazo', 'Riobamba', 'Gasolinera PyS San Alfonso', '🟡 NORMAL', '220V 32A Pata Gallina', '7kW', '24/7', 'Gratuito*', 'https://maps.app.goo.gl/tCU2LPrH6QqmjZrf7', -1.6714943, -78.644216);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Sierra', 'Chimborazo', 'Colta', 'Gasolinera Primax', '🔴 LENTO', '110V 16A', '1.5kW', '24/7', 'Gratuito*', 'https://maps.app.goo.gl/trnWEiyHAnTHKNrQA', -1.7258022, -78.7635487);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Sierra', 'Chimborazo', 'Pallatanga', 'Auto Diesel Su Amigo', '🟡 NORMAL', '220V 32A Pata Gallina', '7kW', '24/7', 'Gratuito*', 'https://maps.app.goo.gl/jTq4JKB3KSMLQTdR7', -2.0093569, -78.9754339);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Sierra', 'Azuay', 'Molleturo', 'Mestizo Restaurant', '🟡 NORMAL', '220V 32A Pata Gallina', '7kW', '24/7', 'Gratuito*', 'https://maps.app.goo.gl/oo9v6276n3UuxW8g6', -2.7582503, -79.401931);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Sierra', 'Azuay', 'Cuenca', 'BYD Cuenca', '🟡 NORMAL', 'Tipo 2 Pared', '7kW', 'Lun-Vie 9am-6pm / Sáb 10am-2pm', 'Pago', 'https://maps.app.goo.gl/jGRZWCi2Yxd3RPuW8', -2.8942, -78.9969749);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Sierra', 'Azuay', 'Cuenca', 'Centro Comercial Milenium Plaza', '🟡 NORMAL', 'Tipo 1 + Tipo 2', '7kW', '10am-10pm', 'Gratuito*', 'https://maps.app.goo.gl/djr57sEAifRfoMht8', -2.9045589, -79.0057164);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Sierra', 'Azuay', 'Cuenca', 'Parque de la Madre', '🟡 NORMAL', 'Tipo 1 + Tipo 2', '7kW', 'Hasta 9pm (subsuelo) y 24/7', 'Gratuito*', 'https://maps.app.goo.gl/djr57sEAifRfoMht8', -2.9045589, -79.0057164);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Sierra', 'Azuay', 'Cuenca', 'Hotel Zahir', '🟡 NORMAL', 'Tipo 2 Pared', '7kW', '24/7', 'Gratuito*', 'https://maps.app.goo.gl/dogjqj2zza4AEpqh6', -2.9055559, -79.0063849);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Sierra', 'Azuay', 'Cuenca', 'Quality Centro Automotriz', '🟡 NORMAL', 'Tipo 2 Pared', '7kW', 'Lun-Sáb 8am-5pm / Sáb 8am-12pm', 'Pago', 'https://maps.app.goo.gl/WTSkjXb6F7HAsRyb7', -2.9099199, -79.0368311);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Sierra', 'Azuay', 'Cuenca', 'Dos Chorreras Restaurant', '🟡 NORMAL', '220V + Tipo 2', '7kW', '10am-9pm', 'Gratuito*', 'https://maps.app.goo.gl/ha7dfdjBUuSiq8vf9', -2.8236329, -79.2137907);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Sierra', 'Azuay', 'Cuenca', 'Empresa Eléctrica Regional Centro Sur', '🟡 NORMAL', 'Tipo 2 Pared', '7kW', 'Tarde', 'Gratuito*', 'https://maps.app.goo.gl/LAHce2fBoKvfGiXe9', -2.9047011, -78.9874177);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Sierra', 'Azuay', 'Cuenca', 'Villa Ana María', '🟡 NORMAL', 'Tipo 2 Pared', '7kW', 'Tarde', 'Gratuito*', 'https://maps.app.goo.gl/qaJPu5ftpNoTQt6p6', -2.8444669, -78.9051243);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Sierra', 'Azuay', 'Cuenca', 'Wayra Plaza — CONDOR CHARGE', '🟢 RÁPIDA', 'CS2 + CHAdeMO + CS1 + Tipo 2', '90kW', '10am-9pm', 'Pago', 'https://maps.app.goo.gl/osyengq8zLkGtydAA', -2.9136766, -78.9895764);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Sierra', 'Cañar', 'Cañar', 'Vulcanizadora', '🟡 NORMAL', '220V 32A Tipo Normal', '7kW', 'Tarde', 'Gratuito*', 'https://maps.app.goo.gl/EjSjLzySEQWDZB4n9', -2.57094, -78.9337916);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Sierra', 'Loja', 'Loja', 'Estadio Federativo Reina de El Cisne — Electrolinera', '🟢 RÁPIDA', 'CHAdeMO (necesita adaptador)', '40kW', '24/7', 'Pago', 'https://maps.app.goo.gl/LgcCetriFRAptYRT7', -4.000992, -79.1965307);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Sierra', 'Loja', 'Loja', 'Punto Carga Comunidad BYD', '⚫ PRIVADO', 'Tipo 2 Pared', '7kW', '24/7 — Agendar', 'Solo miembros BYD', 'RESERVADO - SOLO MIEMBROS BYD', NULL, NULL);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Sierra', 'Loja', 'Saraguro', 'Taller Eléctrico Manuel Tene', '🟡 NORMAL', '220V 32A Pata Gallina', '7kW', 'Tarde', 'Gratuito*', 'https://maps.app.goo.gl/WfSe9iTcxfG2TZxk7', -3.6267708, -79.2408421);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Sierra', 'Bolívar', 'San Pablo de Atenas', 'Estación de Servicio Los Arrayanes', '🟡 NORMAL', '220V 16A Tipo Chino', '3.5kW', '24/7', 'Gratuito*', 'https://maps.app.goo.gl/uhWUeLKxuYiM1nZC9', -1.8050354, -79.0909551);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Sierra', 'Bolívar', 'Guaranda — San Miguel', 'Vulcanizadora cerca Gasolinera PSP', '🟡 NORMAL', '220V 32A Pata Gallina', '7kW', 'Tarde', 'Gratuito*', 'https://maps.app.goo.gl/vhrkxo5wBBUtHWKe8', -1.710272, -79.047983);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Amazonía', 'PROVINCIA', 'CANTÓN / CIUDAD', 'NOMBRE DEL PUNTO', 'VELOCIDAD', 'TIPO DE CARGADOR', 'POTENCIA', 'HORARIO', 'COSTO', 'ENLACE GPS', NULL, NULL);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Amazonía', 'Napo', 'Archidona', 'Hostería El Paraíso de las Orquídeas — El Bosque de los Monos', '🔴 LENTO', '220V 16A Tipo Chino', '3.5kW', '24/7', 'Gratuito*', 'https://maps.app.goo.gl/AV7q97Ej8jKs7PPJ9', -0.893087, -77.800863);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Amazonía', 'Napo', 'Archidona', 'Estación de Servicio P&S Archidona', '🟡 NORMAL', '220V 32A Pata Gallina', '7kW', '24/7', 'Gratuito*', 'https://maps.app.goo.gl/fXuSmrYXhhKwCzco6', -0.9020084, -77.8059441);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Amazonía', 'Napo', 'Baeza', 'Vulcanizadora El Gato — Frente Gasolinera PSP', '🟡 NORMAL', '220V 32A Pata Gallina', '7kW', 'Tarde', 'Gratuito*', 'https://maps.app.goo.gl/r2YgugEcRLusV41t9', -0.4626845, -77.9182245);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Amazonía', 'Napo', 'Puerto Napo', 'Hamadryade Lodge Hotel', '🟡 NORMAL', 'Tipo 2 Pared', '7kW', '24/7', 'Gratuito*', 'https://maps.app.goo.gl/4hZXQidowSkQpncJA', -1.0349355, -77.7287603);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Amazonía', 'Morona Santiago', 'Méndez', 'Punto Carga Comunidad BYD', '⚫ PRIVADO', 'Tipo 2 Pared', '7kW', '24/7 — Agendar', 'Solo miembros BYD', 'RESERVADO - SOLO MIEMBROS BYD', NULL, NULL);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Ruta Q-G', 'CIUDAD / SECTOR', 'PUNTO DE CARGA', 'VELOCIDAD', 'POTENCIA', 'HORARIO', 'COSTO', 'ENLACE GPS', NULL, NULL, NULL, NULL);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Ruta Q-G', 'Quito — Valle Chillos', 'Supermaxi San Bartolo — CONDOR CHARGE', '🟡 NORMAL', '7kW', '10am-8pm', 'Pago', 'https://maps.app.goo.gl/oStt8aJuTtpXChEC7', NULL, NULL, NULL, NULL);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Ruta Q-G', 'Cerca de Aloag', 'Vulcanizadora Recinto La Virgen', '🟡 NORMAL', '7kW', '24/7', 'Gratuito*', 'https://maps.app.goo.gl/wWewNPJu1orB7fvV6', NULL, NULL, NULL, NULL);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Ruta Q-G', 'Latacunga', 'Restaurante Pepas', '🟡 NORMAL', '7kW', '24/7', 'Gratuito*', 'https://maps.app.goo.gl/534wd5UbkWEZk84E9', NULL, NULL, NULL, NULL);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Ruta Q-G', 'Ambato — Mall de los Andes', 'Mall de los Andes — Electrolinera', '🟢 RÁPIDA', '90kW CS2', '10am-9pm', 'Pago', 'https://maps.app.goo.gl/ZrMmFxQ41KDCWAWS9', NULL, NULL, NULL, NULL);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Ruta Q-G', 'Pelileo', 'Gasolinera PRIMAX Panamericana', '🟢 RÁPIDA', '50kW Multi', '24/7', 'Pago', 'https://maps.app.goo.gl/TxtHtmJr1eAE1btV8', NULL, NULL, NULL, NULL);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Ruta Q-G', 'Pallatanga', 'Auto Diesel Su Amigo', '🟡 NORMAL', '7kW', '24/7', 'Gratuito*', 'https://maps.app.goo.gl/jTq4JKB3KSMLQTdR7', NULL, NULL, NULL, NULL);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Ruta Q-G', 'Bucay', 'Cascada La Poderosa', '🟡 NORMAL', '7kW', 'Hasta tarde', 'Gratuito*', 'https://maps.app.goo.gl/qdR55sDkETPKqKkA9', NULL, NULL, NULL, NULL);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Ruta Q-G', 'Patricia Pilar — Los Ríos', 'Vulcanizadora', '🟡 NORMAL', '7kW', 'Tarde', 'Gratuito*', 'https://goo.gl/maps/NTV8uTJyumMSdgnX8', NULL, NULL, NULL, NULL);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Ruta Q-G', 'Santo Domingo', 'KFC / BYD Bomboli — EVINKA CONECT', '🟢 RÁPIDA', '60kW CS2', '24/7', 'Pago', 'https://maps.app.goo.gl/jRtjsbneP1PCLcXx8', NULL, NULL, NULL, NULL);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Ruta Q-G', 'Guayaquil — Parque Samanes', 'CONDOR CHARGE', '🟢 RÁPIDA', '40kW CS2+CHAdeMO', 'No 6pm-10pm', 'Pago', 'https://maps.app.goo.gl/KCp9jK1nZcG49SGF8', NULL, NULL, NULL, NULL);
INSERT INTO public.charging_points (region, province, city_or_canton, name, speed, charger_type, power, schedule, cost_type, gps_link, lat, lng) VALUES ('Ruta Q-G', 'Guayaquil — Salinas/Ceibos', 'Megamaxi Ceibos — CONDOR CHARGE', '🟢 RÁPIDA', '60kW CS2', '9am-9pm', 'Pago', 'https://maps.app.goo.gl/ezQfESXhXVwWkttk7', NULL, NULL, NULL, NULL);
COMMIT;